Update action.yaml

diff --git a/.github/workflows/action.yaml b/.github/workflows/action.yaml
--- a/.github/workflows/action.yaml
+++ b/.github/workflows/action.yaml
@@ -11,10 +11,14 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout code
-      uses: actions/checkout@v2
+      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 
 
-    - name: Run a one-line script
-      run: echo "The PR was merged. Do something here."
-
-    - name: Display custom input
-      run: echo "Custom input is ${{ github.event.pull_request.body }}"
+    - name: Check for custom text
+      run: |
+        PR_BODY="${{ github.event.pull_request.body }}"
+        if [[ "$PR_BODY" == *"your custom text"* ]]; then
+          echo "Custom text is present: $PR_BODY"
+        else
+          echo "Custom text is not present in PR body. Failing the workflow."
+          exit 1
+        fi
